### ISSUE TITLE
App is not available in some languages with all string already translated in Pontoon

### ISSUE THREAD

**Issue by isabelrios** [mozilla-lockwise/lockwise-android#1114]
## Steps to reproduce
Use your device in Russian for example
### Expected behavior
The app should appear in that language
### Actual behavior
The app is in English
### Device & build information
* Device: Pixel 3
* Build version: RC2 v3.3.0 or master
### Notes
Attachments: See screenshots generated:
https://storage.googleapis.com/l10n-lockwise-android/2019-12-17/android/screenshots.html

The app is translated for: "es-ES", "fr-FR", "it-IT", "de-DE", "en-US", "vi-VN"
https://storage.googleapis.com/l10n-lockwise-android/2019-12-16/android/screenshots.html

But not for Russian, not sure which other languages should be already available but looks like at least this new one should be working according to @Delphine (slack conversation), ccing you in case you have more info to add here. Thanks!

**Comment by ddurst** [comment]
Ref #1008

**Comment by Pike** [comment]
This was a bug in the automation script, https://github.com/mozilla-l10n/android-l10n-tooling/issues/19.

Next update to #976 should have this.

**Comment by isabelrios** [comment]
Thanks @Pike! Looks like with that the app will appear correctly translated. I used that branch to get the new set of screenshots including those languages @Delphine: 
https://storage.googleapis.com/l10n-lockwise-android/2019-12-18/android/screenshots.html

If you agree, let's keep this issue open until that is merged in master just to be sure we track it until is merged.

**Comment by Delphine** [comment]
This is super helpful, thank you very much. Let's totally keep this open and close this issue once thinks are fixed for sure.

**Comment by eliserichards** [comment]
We merged the last round of l10n changes. Is this still valid @Pike ?

**Comment by Delphine** [comment]
I think we should double check that the latest builds have all the languages now. Not sure when these changes will be available to check on device?

**Comment by isabelrios** [comment]
@Delphine @eliserichards Let me try to get all the screenshots in all the locales from master and will comment here with the result.

**Comment by isabelrios** [comment]
I think this issue can be closed. Running the script to get the locales on master is working and the app is translated in these languages:

locales ["es-ES", "fr-FR", "it-IT", "de-DE", "en-US", "vi-VN", "cs", "ru"]

@Delphine Are we still missing some locales? I'm going to create a PR to add "cs" and "ru" to the [Screengrab](https://github.com/mozilla-lockwise/lockwise-android/blob/master/fastlane/Screengrabfile#L11) file

**Comment by Delphine** [comment]
There seems to be some locales missing.
Basically, it should be these: 
  "cs",
  "de",
  "en-GB",
  "es",
  "fr",
  "it",
  "ru",
  "uk",
  "vi",
  "zh-TW"

You can check exactly which locales are in Lockwise Android from the .toml file found here: https://github.com/mozilla-l10n/android-l10n/blob/master/mozilla-lockwise/lockwise-android/l10n.toml
(I realize from our discussion this morning that finding out from Pontoon which locales are contained as part of android-l10n products is more complicated than for all other projects - I'll sync up with you Isabel on Slack about this to clarify. Sorry for the confusion)

**Comment by isabelrios** [comment]
The list is now complete in the PR :) thanks Delphine for the updated list. I will check that file in the future
